matrix:
    include:
        - os: linux
          language: generic
          sudo: required
          dist: trusty
script:
before_install:
    - ./maintainers/travis-build.sh nix
script:
    - ./maintainers/travis-build.sh build
